# Generated by Django 4.2rc1 on 2023-03-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_comments_xtd", "0008_auto_20200920_2037"),
    ]

    operations = [
        migrations.AddField(
            model_name="xtdcomment",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("normal", "普通评论"), ("remind", "催一催")],
                default="normal",
                max_length=16,
                verbose_name="评论类型",
            ),
        ),
    ]
